//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/5282246_4_SolSiege/SimpleControl.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @SimpleControl: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @SimpleControl()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""SimpleControl"",
    ""maps"": [
        {
            ""name"": ""GameplayControl"",
            ""id"": ""4260eddb-6464-4082-959d-3ee28ba0fb50"",
            ""actions"": [
                {
                    ""name"": ""mousePoition"",
                    ""type"": ""Value"",
                    ""id"": ""b4c9e40b-94e9-4f3d-b38e-714ebe331f84"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""mouseButton"",
                    ""type"": ""Value"",
                    ""id"": ""34ba4d78-f768-49e4-bdbf-14c4a8455e2e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""97270638-fc61-492e-a29f-8f9f5bcca170"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""mousePoition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""052f0a94-3ac4-4962-bf88-9ff1fa46fc1e"",
                    ""path"": ""<Touchscreen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""mousePoition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e64a183e-2f4d-4c4e-b76d-fe58c67dec38"",
                    ""path"": ""<Pointer>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""mousePoition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a01d305b-7e8c-441b-aa4e-c47681ac3028"",
                    ""path"": ""<Pointer>/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""mouseButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0880d207-87dc-4d06-b375-a99e74c95ad1"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""mouseButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""32ca0608-2404-4d9c-b7bd-bf54d4238c21"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""mouseButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GameplayControl
        m_GameplayControl = asset.FindActionMap("GameplayControl", throwIfNotFound: true);
        m_GameplayControl_mousePoition = m_GameplayControl.FindAction("mousePoition", throwIfNotFound: true);
        m_GameplayControl_mouseButton = m_GameplayControl.FindAction("mouseButton", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GameplayControl
    private readonly InputActionMap m_GameplayControl;
    private List<IGameplayControlActions> m_GameplayControlActionsCallbackInterfaces = new List<IGameplayControlActions>();
    private readonly InputAction m_GameplayControl_mousePoition;
    private readonly InputAction m_GameplayControl_mouseButton;
    public struct GameplayControlActions
    {
        private @SimpleControl m_Wrapper;
        public GameplayControlActions(@SimpleControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @mousePoition => m_Wrapper.m_GameplayControl_mousePoition;
        public InputAction @mouseButton => m_Wrapper.m_GameplayControl_mouseButton;
        public InputActionMap Get() { return m_Wrapper.m_GameplayControl; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayControlActions set) { return set.Get(); }
        public void AddCallbacks(IGameplayControlActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayControlActionsCallbackInterfaces.Add(instance);
            @mousePoition.started += instance.OnMousePoition;
            @mousePoition.performed += instance.OnMousePoition;
            @mousePoition.canceled += instance.OnMousePoition;
            @mouseButton.started += instance.OnMouseButton;
            @mouseButton.performed += instance.OnMouseButton;
            @mouseButton.canceled += instance.OnMouseButton;
        }

        private void UnregisterCallbacks(IGameplayControlActions instance)
        {
            @mousePoition.started -= instance.OnMousePoition;
            @mousePoition.performed -= instance.OnMousePoition;
            @mousePoition.canceled -= instance.OnMousePoition;
            @mouseButton.started -= instance.OnMouseButton;
            @mouseButton.performed -= instance.OnMouseButton;
            @mouseButton.canceled -= instance.OnMouseButton;
        }

        public void RemoveCallbacks(IGameplayControlActions instance)
        {
            if (m_Wrapper.m_GameplayControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameplayControlActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameplayControlActions @GameplayControl => new GameplayControlActions(this);
    public interface IGameplayControlActions
    {
        void OnMousePoition(InputAction.CallbackContext context);
        void OnMouseButton(InputAction.CallbackContext context);
    }
}
